#!/usr/bin/env bash
# A script that gives information about a file

file="school"

# checks if file exists
if [ -e "$file" ]
then
  echo "$file file exists"

  # if file is not empty
  if [ ! -s "$file" ]
  then
    echo "$file file is empty"

    # checks if file is a regular file
    if [ -f "$file" ]
    then
      echo "$file is a regular file"
    fi
  else
    echo "$file file is not empty"

    # checks if file is a regular file
    if [ -f "$file" ]
    then
      echo "$file is a regular file"
    fi
  fi
else
  echo "$file file does not exist"
fi
